In [1]:
import pandas as pd

In [2]:
data = pd.read_csv("rainfall.csv")
df = pd.DataFrame(data)
df = df.drop("rainfall",axis = 1)
df

          date  temperature  humidity  wind_speed weather_condition
0   2022-01-01         15.2      78.0         8.5             Rainy
1   2022-01-02         17.8      65.0         5.2             Rainy
2   2022-01-03         20.1      52.0         3.1             Sunny
3   2022-01-04         18.6      71.0         6.7             Rainy
4   2022-01-05         14.8      82.0         9.3             Rainy
5   2022-01-06         16.5      75.0         7.8             Rainy
6   2022-01-07         19.2      61.0         4.5             Rainy
7   2022-01-08         21.7      48.0         2.9             Sunny
8   2022-01-09         17.3      73.0         6.1             Rainy
9   2022-01-10         15.8      79.0         8.9             Rainy
10  2022-01-11         16.2      72.0         5.7             Rainy
11  2022-01-12         19.8      58.0         3.5             Rainy
12  2022-01-13         22.4      45.0         2.1             Sunny
13  2022-01-14         17.9      69.0         6.5             Rainy
14  2022-01-15         15.1      81.0         8.7             Rainy
15  2022-01-16         16.8      77.0         7.2             Rainy
16  2022-01-17         18.5      63.0         4.9             Rainy
17  2022-01-18         21.2      51.0         3.3             Sunny
18  2022-01-19         17.6      75.0         6.7             Rainy
19  2022-01-20         14.5      84.0         9.1             Rainy
20  2022-01-21         16.1      71.0         5.3             Rainy
21  2022-01-22         19.4      59.0         4.1             Sunny
22  2022-01-23         18.2      67.0         7.1             Rainy
23  2022-01-24         15.7      79.0         8.3             Rainy
24  2022-01-25         17.1      76.0         6.8             Rainy
25  2022-01-26         19.7      62.0         4.7             Rainy
26  2022-01-27         22.9      47.0         2.5             Sunny
27  2022-01-28         18.5      70.0         7.3             Rainy
28  2022-01-29         14.2      83.0         9.5             Rainy
29  2022-01-30         16.4      78.0         7.6             Rainy
30  2022-01-31         19.1      65.0         5.1             Rainy
31  2022-02-01         21.6      53.0         3.7             Sunny
32  2022-02-02         17.2      73.0         7.5             Rainy
33  2022-02-03         15.4      81.0         8.9             Rainy
34  2022-02-04         16.7      77.0         6.2             Rainy
35  2022-02-05         18.9      64.0         4.3             Rainy
36  2022-02-06         22.1      49.0         2.7             Sunny
37  2022-02-07         17.8      72.0         6.9             Rainy
38  2022-02-08         14.7      85.0         9.3             Rainy
39  2022-02-09         16.2      79.0         7.8             Rainy
40  2022-02-10         19.5      66.0         5.5             Rainy
41  2022-02-11         23.4      44.0         3.1             Sunny
42  2022-02-12         18.1      74.0         7.7             Rainy
43  2022-02-13         13.9      87.0         9.9             Rainy
44  2022-02-14         15.6      81.0         8.2             Rainy
45  2022-02-15         19.2      68.0         6.1             Rainy
46  2022-02-16         22.7      51.0         4.5             Sunny
47  2022-02-17         17.4      75.0         8.3             Rainy
48  2022-02-18         14.1      89.0        10.5             Rainy
49  2022-02-19         15.9      83.0         8.6             Rainy
50  2022-02-20         18.6      71.0         6.7             Rainy
51  2022-02-21         21.3      55.0         5.1             Sunny
52  2022-02-22         16.8      77.0         8.9             Rainy
53          Co          NaN       NaN         NaN               NaN

In [3]:
df.columns

Index(['date', 'temperature', 'humidity', 'wind_speed', 'weather_condition'], dtype='str')

In [4]:
df.describe()

       temperature   humidity  wind_speed
count    53.000000  53.000000   53.000000
mean     17.950943  69.245283    6.403774
std       2.500663  11.969361    2.209069
min      13.900000  44.000000    2.100000
25%      16.100000  62.000000    4.700000
50%      17.800000  72.000000    6.700000
75%      19.400000  78.000000    8.300000
max      23.400000  89.000000   10.500000

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 54 entries, 0 to 53
Data columns (total 5 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   date               54 non-null     str
 1   temperature        53 non-null     float64
 2   humidity           53 non-null     float64
 3   wind_speed         53 non-null     float64
 4   weather_condition  53 non-null     str
dtypes: float64(3), str(2)
memory usage: 2.2 KB

In [6]:
df.size

270

In [7]:
df.isnull().sum()

date                 0
temperature          1
humidity             1
wind_speed           1
weather_condition    1
dtype: int64

In [8]:
df = df.drop("date",axis = 1)
df

    temperature  humidity  wind_speed weather_condition
0          15.2      78.0         8.5             Rainy
1          17.8      65.0         5.2             Rainy
2          20.1      52.0         3.1             Sunny
3          18.6      71.0         6.7             Rainy
4          14.8      82.0         9.3             Rainy
5          16.5      75.0         7.8             Rainy
6          19.2      61.0         4.5             Rainy
7          21.7      48.0         2.9             Sunny
8          17.3      73.0         6.1             Rainy
9          15.8      79.0         8.9             Rainy
10         16.2      72.0         5.7             Rainy
11         19.8      58.0         3.5             Rainy
12         22.4      45.0         2.1             Sunny
13         17.9      69.0         6.5             Rainy
14         15.1      81.0         8.7             Rainy
15         16.8      77.0         7.2             Rainy
16         18.5      63.0         4.9             Rainy
17         21.2      51.0         3.3             Sunny
18         17.6      75.0         6.7             Rainy
19         14.5      84.0         9.1             Rainy
20         16.1      71.0         5.3             Rainy
21         19.4      59.0         4.1             Sunny
22         18.2      67.0         7.1             Rainy
23         15.7      79.0         8.3             Rainy
24         17.1      76.0         6.8             Rainy
25         19.7      62.0         4.7             Rainy
26         22.9      47.0         2.5             Sunny
27         18.5      70.0         7.3             Rainy
28         14.2      83.0         9.5             Rainy
29         16.4      78.0         7.6             Rainy
30         19.1      65.0         5.1             Rainy
31         21.6      53.0         3.7             Sunny
32         17.2      73.0         7.5             Rainy
33         15.4      81.0         8.9             Rainy
34         16.7      77.0         6.2             Rainy
35         18.9      64.0         4.3             Rainy
36         22.1      49.0         2.7             Sunny
37         17.8      72.0         6.9             Rainy
38         14.7      85.0         9.3             Rainy
39         16.2      79.0         7.8             Rainy
40         19.5      66.0         5.5             Rainy
41         23.4      44.0         3.1             Sunny
42         18.1      74.0         7.7             Rainy
43         13.9      87.0         9.9             Rainy
44         15.6      81.0         8.2             Rainy
45         19.2      68.0         6.1             Rainy
46         22.7      51.0         4.5             Sunny
47         17.4      75.0         8.3             Rainy
48         14.1      89.0        10.5             Rainy
49         15.9      83.0         8.6             Rainy
50         18.6      71.0         6.7             Rainy
51         21.3      55.0         5.1             Sunny
52         16.8      77.0         8.9             Rainy
53          NaN       NaN         NaN               NaN

In [9]:
df = df.iloc[:-1]
df

    temperature  humidity  wind_speed weather_condition
0          15.2      78.0         8.5             Rainy
1          17.8      65.0         5.2             Rainy
2          20.1      52.0         3.1             Sunny
3          18.6      71.0         6.7             Rainy
4          14.8      82.0         9.3             Rainy
5          16.5      75.0         7.8             Rainy
6          19.2      61.0         4.5             Rainy
7          21.7      48.0         2.9             Sunny
8          17.3      73.0         6.1             Rainy
9          15.8      79.0         8.9             Rainy
10         16.2      72.0         5.7             Rainy
11         19.8      58.0         3.5             Rainy
12         22.4      45.0         2.1             Sunny
13         17.9      69.0         6.5             Rainy
14         15.1      81.0         8.7             Rainy
15         16.8      77.0         7.2             Rainy
16         18.5      63.0         4.9             Rainy
17         21.2      51.0         3.3             Sunny
18         17.6      75.0         6.7             Rainy
19         14.5      84.0         9.1             Rainy
20         16.1      71.0         5.3             Rainy
21         19.4      59.0         4.1             Sunny
22         18.2      67.0         7.1             Rainy
23         15.7      79.0         8.3             Rainy
24         17.1      76.0         6.8             Rainy
25         19.7      62.0         4.7             Rainy
26         22.9      47.0         2.5             Sunny
27         18.5      70.0         7.3             Rainy
28         14.2      83.0         9.5             Rainy
29         16.4      78.0         7.6             Rainy
30         19.1      65.0         5.1             Rainy
31         21.6      53.0         3.7             Sunny
32         17.2      73.0         7.5             Rainy
33         15.4      81.0         8.9             Rainy
34         16.7      77.0         6.2             Rainy
35         18.9      64.0         4.3             Rainy
36         22.1      49.0         2.7             Sunny
37         17.8      72.0         6.9             Rainy
38         14.7      85.0         9.3             Rainy
39         16.2      79.0         7.8             Rainy
40         19.5      66.0         5.5             Rainy
41         23.4      44.0         3.1             Sunny
42         18.1      74.0         7.7             Rainy
43         13.9      87.0         9.9             Rainy
44         15.6      81.0         8.2             Rainy
45         19.2      68.0         6.1             Rainy
46         22.7      51.0         4.5             Sunny
47         17.4      75.0         8.3             Rainy
48         14.1      89.0        10.5             Rainy
49         15.9      83.0         8.6             Rainy
50         18.6      71.0         6.7             Rainy
51         21.3      55.0         5.1             Sunny
52         16.8      77.0         8.9             Rainy

In [10]:
X = df.drop("weather_condition",axis = 1)
y = df["weather_condition"]
X,y

(    temperature  humidity  wind_speed
 0          15.2      78.0         8.5
 1          17.8      65.0         5.2
 2          20.1      52.0         3.1
 3          18.6      71.0         6.7
 4          14.8      82.0         9.3
 5          16.5      75.0         7.8
 6          19.2      61.0         4.5
 7          21.7      48.0         2.9
 8          17.3      73.0         6.1
 9          15.8      79.0         8.9
 10         16.2      72.0         5.7
 11         19.8      58.0         3.5
 12         22.4      45.0         2.1
 13         17.9      69.0         6.5
 14         15.1      81.0         8.7
 15         16.8      77.0         7.2
 16         18.5      63.0         4.9
 17         21.2      51.0         3.3
 18         17.6      75.0         6.7
 19         14.5      84.0         9.1
 20         16.1      71.0         5.3
 21         19.4      59.0         4.1
 22         18.2      67.0         7.1
 23         15.7      79.0         8.3
 24         17.1      76.0         6.8
 25         19.7      62.0         4.7
 26         22.9      47.0         2.5
 27         18.5      70.0         7.3
 28         14.2      83.0         9.5
 29         16.4      78.0         7.6
 30         19.1      65.0         5.1
 31         21.6      53.0         3.7
 32         17.2      73.0         7.5
 33         15.4      81.0         8.9
 34         16.7      77.0         6.2
 35         18.9      64.0         4.3
 36         22.1      49.0         2.7
 37         17.8      72.0         6.9
 38         14.7      85.0         9.3
 39         16.2      79.0         7.8
 40         19.5      66.0         5.5
 41         23.4      44.0         3.1
 42         18.1      74.0         7.7
 43         13.9      87.0         9.9
 44         15.6      81.0         8.2
 45         19.2      68.0         6.1
 46         22.7      51.0         4.5
 47         17.4      75.0         8.3
 48         14.1      89.0        10.5
 49         15.9      83.0         8.6
 50         18.6      71.0         6.7
 51         21.3      55.0         5.1
 52         16.8      77.0         8.9,
 0     Rainy
 1     Rainy
 2     Sunny
 3     Rainy
 4     Rainy
 5     Rainy
 6     Rainy
 7     Sunny
 8     Rainy
 9     Rainy
 10    Rainy
 11    Rainy
 12    Sunny
 13    Rainy
 14    Rainy
 15    Rainy
 16    Rainy
 17    Sunny
 18    Rainy
 19    Rainy
 20    Rainy
 21    Sunny
 22    Rainy
 23    Rainy
 24    Rainy
 25    Rainy
 26    Sunny
 27    Rainy
 28    Rainy
 29    Rainy
 30    Rainy
 31    Sunny
 32    Rainy
 33    Rainy
 34    Rainy
 35    Rainy
 36    Sunny
 37    Rainy
 38    Rainy
 39    Rainy
 40    Rainy
 41    Sunny
 42    Rainy
 43    Rainy
 44    Rainy
 45    Rainy
 46    Sunny
 47    Rainy
 48    Rainy
 49    Rainy
 50    Rainy
 51    Sunny
 52    Rainy
 Name: weather_condition, dtype: str)

In [11]:
from sklearn.model_selection import train_test_split

X_train,X_test,y_train,y_test = train_test_split(X,y,test_size = 0.2,random_state = 42)

In [12]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)
X_train,X_test

(array([[-0.23473222,  0.29982564, -0.13720203],
        [ 2.14496686, -2.02222824, -1.83760758],
        [ 0.57266568, -0.77189154, -0.89293783],
        [-0.48969998,  0.6570647 , -0.08996855],
        [-1.29709788,  1.10361352,  1.37426956],
        [-0.02225909,  0.21051587,  0.24066586],
        [-0.31972148,  0.56775493,  0.19343238],
        [-0.95714087,  1.01430376,  0.8547012 ],
        [-1.04213013,  1.01430376,  1.18533561],
        [-0.82965699,  1.19292329,  1.04363515],
        [-0.44720535,  0.6570647 ,  0.38236633],
        [-0.87215162,  0.83568423,  1.18533561],
        [ 0.2752033 , -0.59327201, -0.70400388],
        [ 0.53017105, -0.41465248, -0.60953691],
        [ 1.80500985, -1.84360872, -1.74314061],
        [ 0.78513881, -0.68258177, -0.79847086],
        [ 0.82763344, -1.03982083, -1.36527271],
        [-1.12711938,  0.74637446,  0.99640166],
        [ 2.05997761, -1.66498919, -0.89293783],
        [ 0.2752033 ,  0.03189634,  0.42959981],
        [ 1.59253672, -1.48636966, -1.27080573],
        [-0.70217311,  0.83568423,  0.66576725],
        [-0.61718386,  0.74637446,  0.57130028],
        [ 0.57266568, -0.14672318, -0.13720203],
        [-0.02225909, -0.41465248, -0.56230342],
        [ 0.65765493, -0.95051107, -1.08187178],
        [ 0.95511732, -1.57567942, -1.55420666],
        [ 0.70014956, -0.32534271, -0.42060296],
        [ 0.4451818 , -0.50396224, -0.98740481],
        [-0.91464625,  0.83568423,  0.90193469],
        [-1.59456027,  1.72878187,  1.94107141],
        [-0.70217311,  0.21051587, -0.32613598],
        [ 0.14771942, -0.23603295,  0.33513284],
        [-0.10724834,  0.47844517,  0.14619889],
        [-0.44720535,  0.6570647 ,  1.18533561],
        [-0.74466774,  0.12120611, -0.51506993],
        [ 1.63503134, -1.93291848, -1.64867363],
        [ 0.10522479,  0.3891354 ,  0.61853376],
        [-1.16961401,  1.01430376,  1.09086864],
        [-1.55206564,  1.19292329,  1.46873654],
        [ 1.46505284, -1.30775013, -0.60953691],
        [-1.33959251,  1.37154282,  1.37426956]]),
 array([[-1.42458176,  1.28223305,  1.27980259],
        [ 2.35743999, -2.29015754, -1.55420666],
        [-0.1922376 ,  0.47844517,  0.90193469],
        [ 1.93249373, -2.20084777, -2.02654153],
        [-1.67954952,  1.55016235,  1.65767049],
        [-0.57468923,  0.47844517,  0.66576725],
        [ 1.42255821, -1.66498919, -1.45973968],
        [ 0.31769792,  0.12120611,  0.14619889],
        [ 0.31769792,  0.12120611,  0.14619889],
        [-0.27722685,  0.29982564,  0.52406679],
        [ 0.02023554, -0.05741342,  0.05173191]]))

In [13]:
from sklearn.neighbors import KNeighborsClassifier

model = KNeighborsClassifier()
model.fit(X_train,y_train)
y_pred = model.predict(X_test)
y_pred

array(['Rainy', 'Sunny', 'Rainy', 'Sunny', 'Rainy', 'Rainy', 'Sunny',
       'Rainy', 'Rainy', 'Rainy', 'Rainy'], dtype=object)

In [14]:
from sklearn.metrics import accuracy_score

print(accuracy_score(y_test,y_pred))

1.0