In [16]:
import pandas as pd
from pathlib import Path

In [17]:
df_02 = pd.DataFrame(pd.read_csv("D:/My_projects/Capstone_project/data/raw/02_nav_history.csv"))
df_02

       amfi_code        date       nav
0         119551  2022-01-03   54.3856
1         119551  2022-01-04   54.3474
2         119551  2022-01-05   54.6869
3         119551  2022-01-06   55.4550
4         119551  2022-01-07   55.3692
...          ...         ...       ...
45995     149324  2026-05-25  292.4810
45996     149324  2026-05-26  291.2707
45997     149324  2026-05-27  288.8007
45998     149324  2026-05-28  280.6873
45999     149324  2026-05-29  279.7511

[46000 rows x 3 columns]

In [18]:
df_02.shape

(46000, 3)

In [19]:
df_02.columns

Index(['amfi_code', 'date', 'nav'], dtype='str')

In [20]:
df_02.info()

<class 'pandas.DataFrame'>
RangeIndex: 46000 entries, 0 to 45999
Data columns (total 3 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   amfi_code  46000 non-null  int64
 1   date       46000 non-null  str
 2   nav        46000 non-null  float64
dtypes: float64(1), int64(1), str(1)
memory usage: 1.1 MB

In [21]:
df_02.describe(include="all")

            amfi_code        date           nav
count    46000.000000       46000  46000.000000
unique            NaN        1150           NaN
top               NaN  2022-01-03           NaN
freq              NaN          40           NaN
mean    120247.000000         NaN    269.570265
std      14352.317221         NaN    577.187060
min     100016.000000         NaN     26.136600
25%     118632.750000         NaN     69.170425
50%     119551.500000         NaN    122.732150
75%     120842.250000         NaN    260.338675
max     149324.000000         NaN   4268.549700

In [22]:
df_02.head()

   amfi_code        date      nav
0     119551  2022-01-03  54.3856
1     119551  2022-01-04  54.3474
2     119551  2022-01-05  54.6869
3     119551  2022-01-06  55.4550
4     119551  2022-01-07  55.3692

In [23]:
df_02.tail()

       amfi_code        date       nav
45995     149324  2026-05-25  292.4810
45996     149324  2026-05-26  291.2707
45997     149324  2026-05-27  288.8007
45998     149324  2026-05-28  280.6873
45999     149324  2026-05-29  279.7511

In [24]:
df_02.dtypes

amfi_code      int64
date             str
nav          float64
dtype: object

In [25]:
df_02.isna().sum()

amfi_code    0
date         0
nav          0
dtype: int64

In [26]:
df_02.duplicated().sum()

np.int64(0)

In [27]:
df_02["date"] = pd.to_datetime(
    df_02["date"],
    errors="coerce",
    dayfirst=True
)

In [28]:
df_02 = df_02.sort_values(
    ["amfi_code", "date"]
)

In [29]:
print("NAV values <= 0:", (df_02["nav"] <= 0).sum())

NAV values <= 0: 0

In [30]:
processed_path = Path("../data/processed")
processed_path.mkdir(parents=True, exist_ok=True)

df_02.to_csv(
    processed_path / "nav_history.csv",
    index=False
)