In [1]:
import pandas as pd

In [2]:
df_05 = pd.DataFrame(pd.read_csv("D:/My_projects/Capstone_project/data/raw/05_category_inflows.csv"))
df_05

       month           category  net_inflow_crore
0    2024-04          Large Cap            2413.0
1    2024-04            Mid Cap            3897.0
2    2024-04          Small Cap            3533.0
3    2024-04          Flexi Cap            4947.0
4    2024-04    Large & Mid Cap            4214.0
..       ...                ...               ...
139  2025-03  Sectoral/Thematic            8614.0
140  2025-03             Liquid           38681.0
141  2025-03     Short Duration            4886.0
142  2025-03               Gilt             956.0
143  2025-03             Hybrid            2830.0

[144 rows x 3 columns]

In [3]:
df_05.shape

(144, 3)

In [4]:
df_05.columns

Index(['month', 'category', 'net_inflow_crore'], dtype='str')

In [5]:
df_05.dtypes

month                   str
category                str
net_inflow_crore    float64
dtype: object

In [6]:
df_05.head()

     month         category  net_inflow_crore
0  2024-04        Large Cap            2413.0
1  2024-04          Mid Cap            3897.0
2  2024-04        Small Cap            3533.0
3  2024-04        Flexi Cap            4947.0
4  2024-04  Large & Mid Cap            4214.0

In [7]:
df_05.tail()

       month           category  net_inflow_crore
139  2025-03  Sectoral/Thematic            8614.0
140  2025-03             Liquid           38681.0
141  2025-03     Short Duration            4886.0
142  2025-03               Gilt             956.0
143  2025-03             Hybrid            2830.0

In [8]:
df_05.info()

<class 'pandas.DataFrame'>
RangeIndex: 144 entries, 0 to 143
Data columns (total 3 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   month             144 non-null    str
 1   category          144 non-null    str
 2   net_inflow_crore  144 non-null    float64
dtypes: float64(1), str(2)
memory usage: 3.5 KB

In [9]:
df_05.describe(include="all")

          month   category  net_inflow_crore
count       144        144        144.000000
unique       12         12               NaN
top     2024-04  Large Cap               NaN
freq         12         12               NaN
mean        NaN        NaN       6473.881944
std         NaN        NaN       9718.335947
min         NaN        NaN        437.000000
25%         NaN        NaN       1801.250000
50%         NaN        NaN       4148.000000
75%         NaN        NaN       5304.000000
max         NaN        NaN      41952.000000

In [10]:
df_05.isna().sum()

month               0
category            0
net_inflow_crore    0
dtype: int64

In [11]:
df_05.duplicated().sum()

np.int64(0)