In [ ]:
import pandas as pd
from pathlib import Path

In [ ]:
df_10 = pd.DataFrame(pd.read_csv("D:/My_projects/Capstone_project/data/raw/09_portfolio_holdings.csv"))
df_10

,amfi_code,stock_symbol,stock_name,sector,weight_pct,market_value_cr,current_price_inr,portfolio_date
0,119551,POWERGRID,Power Grid Corporation,Utilities,13.85,737.09,6011.08,2025-12-31
1,119551,HDFCBANK,HDFC Bank Ltd,Banking,11.19,88.97,1074.65,2025-12-31
2,119551,GRASIM,Grasim Industries Ltd,Diversified,9.90,208.45,5964.59,2025-12-31
3,119551,DRREDDY,Dr. Reddy's Laboratories,Pharma,4.76,161.32,3748.82,2025-12-31
4,119551,ASIANPAINT,Asian Paints Ltd,Paints,10.25,725.90,1321.45,2025-12-31
...,...,...,...,...,...,...,...,...
317,149324,DIVISLAB,Divi's Laboratories,Pharma,9.54,855.88,7453.05,2025-12-31
318,149324,BHARTIARTL,Bharti Airtel Ltd,Telecom,1.79,969.71,924.41,2025-12-31
319,149324,TCS,Tata Consultancy Services,IT,13.17,1637.69,1927.89,2025-12-31
320,149324,INDUSINDBK,IndusInd Bank Ltd,Banking,7.63,1387.30,3208.86,2025-12-31
321,149324,NTPC,NTPC Ltd,Utilities,2.04,1303.55,5797.95,2025-12-31

In [ ]:
df_10.head()

,amfi_code,stock_symbol,stock_name,sector,weight_pct,market_value_cr,current_price_inr,portfolio_date
0,119551,POWERGRID,Power Grid Corporation,Utilities,13.85,737.09,6011.08,2025-12-31
1,119551,HDFCBANK,HDFC Bank Ltd,Banking,11.19,88.97,1074.65,2025-12-31
2,119551,GRASIM,Grasim Industries Ltd,Diversified,9.90,208.45,5964.59,2025-12-31
3,119551,DRREDDY,Dr. Reddy's Laboratories,Pharma,4.76,161.32,3748.82,2025-12-31
4,119551,ASIANPAINT,Asian Paints Ltd,Paints,10.25,725.90,1321.45,2025-12-31

In [ ]:
df_10.tail()

,amfi_code,stock_symbol,stock_name,sector,weight_pct,market_value_cr,current_price_inr,portfolio_date
317,149324,DIVISLAB,Divi's Laboratories,Pharma,9.54,855.88,7453.05,2025-12-31
318,149324,BHARTIARTL,Bharti Airtel Ltd,Telecom,1.79,969.71,924.41,2025-12-31
319,149324,TCS,Tata Consultancy Services,IT,13.17,1637.69,1927.89,2025-12-31
320,149324,INDUSINDBK,IndusInd Bank Ltd,Banking,7.63,1387.30,3208.86,2025-12-31
321,149324,NTPC,NTPC Ltd,Utilities,2.04,1303.55,5797.95,2025-12-31

In [ ]:
df_10.shape

(322, 8)

In [ ]:
df_10.columns

Index(['amfi_code', 'stock_symbol', 'stock_name', 'sector', 'weight_pct',
       'market_value_cr', 'current_price_inr', 'portfolio_date'],
      dtype='str')

In [ ]:
df_10.dtypes

amfi_code              int64
stock_symbol             str
stock_name               str
sector                   str
weight_pct           float64
market_value_cr      float64
current_price_inr    float64
portfolio_date           str
dtype: object

In [ ]:
df_10.info()

<class 'pandas.DataFrame'>
RangeIndex: 322 entries, 0 to 321
Data columns (total 8 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   amfi_code          322 non-null    int64
 1   stock_symbol       322 non-null    str
 2   stock_name         322 non-null    str
 3   sector             322 non-null    str
 4   weight_pct         322 non-null    float64
 5   market_value_cr    322 non-null    float64
 6   current_price_inr  322 non-null    float64
 7   portfolio_date     322 non-null    str
dtypes: float64(3), int64(1), str(4)
memory usage: 20.3 KB

In [ ]:
df_10.describe(include="all")

,amfi_code,stock_symbol,stock_name,sector,weight_pct,market_value_cr,current_price_inr,portfolio_date
count,322.000000,322,322,322,322.000000,322.000000,322.000000,322
unique,NaN,30,30,14,NaN,NaN,NaN,1
top,NaN,BHARTIARTL,Bharti Airtel Ltd,Banking,NaN,NaN,NaN,2025-12-31
freq,NaN,15,15,60,NaN,NaN,NaN,322
mean,121210.434783,NaN,NaN,NaN,10.558975,1008.846646,4080.870528,NaN
std,14669.377920,NaN,NaN,NaN,6.060137,543.827535,2265.186353,NaN
min,100016.000000,NaN,NaN,NaN,0.990000,55.740000,246.780000,NaN
25%,118633.000000,NaN,NaN,NaN,6.015000,513.702500,2081.985000,NaN
50%,119552.000000,NaN,NaN,NaN,9.395000,1045.670000,4138.995000,NaN
75%,120842.750000,NaN,NaN,NaN,13.917500,1477.502500,5914.307500,NaN
max,149324.000000,NaN,NaN,NaN,38.180000,1999.500000,7942.960000,NaN

In [ ]:
df_10.isna().sum()

amfi_code            0
stock_symbol         0
stock_name           0
sector               0
weight_pct           0
market_value_cr      0
current_price_inr    0
portfolio_date       0
dtype: int64

In [ ]:
df_10.duplicated().sum()

np.int64(0)

In [ ]:
processed_path = Path("../data/processed")
processed_path.mkdir(parents=True, exist_ok=True)

df_10.to_csv(
    processed_path / "benchmark_indices.csv",
    index=False
)